### PR TITLE
fix(email): Fix SendGrid fallback integration

### LINKED ISSUE #1021: Test Sendgrid
Test Sendgrid as fallback to AWS SES

### PR DESCRIPTION
**Pull request by zwliew**
## Problem

We currently use SendGrid as our email fallback. This causes the
following functions to fail:

1. Verifying custom from addresses (e.g. adding a new address, storing
   a campaign template with a custom address)
2. Sending emails with custom from addresses will fail
3. Receiving delivery report callbacks since the code currently parses the callbacks incorrectly

Closes #1021

## Solution

Since custom from addresses are not verified with SendGrid, we shouldn't use
them at all.

In the future, if we do intend to authenticate custom from addresses with SendGrid,
we will also have to rewire `verifyFromAddress()` to use SendGrid APIs.

**Features**:
1. Send all emails using the default address during the fallback.
2. Disable verification of custom from addresses during the fallback.
3. Disable storing of templates using custom from addresses.
4. Documented instructions to activate the email fallback on the incident response doc
5. Fix parsing of SendGrid webhook events

## Before & After Screenshots

<details>
  <summary>Click to show images</summary>

**AFTER**:
Attempting to verify a custom from address:
Screenshot 2021-03-10 at 9 07 24 AM

Attempting to save an email template using a custom from address:
Screenshot 2021-03-10 at 9 24 54 AM

Creating a new email campaign:
Screenshot 2021-03-10 at 9 03 46 AM
</details>

## Tests

Test 1: all campaign emails should be sent using the default from address during fallback
- Store a campaign using a custom from address
- Set `EMAIL_FALLBACK_ACTIVATE` to `true` for the worker
- Send the campaign
- The campaign emails should be sent using the default from address

Test 2: verification of custom from addresses should be disabled during fallback
- Set `EMAIL_FALLBACK_ACTIVATE` to `true` for the backend
- Try to verify a custom from address
- The UI should display an error message like in the first screenshot above

Test 3: storing of templates with custom from addresses should be disabled during fallback
- Set `EMAIL_FALLBACK_ACTIVATE` to `true` for the backend
- Try to store a campaign using a custom from address
- The UI should display an error message like in the second screenshot above

**Test 4: SES callbacks should be received and parsed correctly**
- [x] Test sending via SES
  1. Deploy the branch on Travis with `STAGING_BRANCH=sendgrid-email-fallback` and `DEPLOY_WORKER=true`
  2. Send an email campaign (using these emails: https://docs.aws.amazon.com/ses/latest/DeveloperGuide/send-email-simulator.html)
  3. Ensure that the `status` and `error_code` columns of the`email_messages` are updated correctly]

**Test 5: SendGrid callbacks should be received and parsed correctly**
- [x] Test sending via SendGrid
  1. Set `EMAIL_FALLBACK_ACTIVATE=true` on Secrets Manager
  2. Prefix the Secrets Manager variables listed below with `BAK_`
  3. Add SendGrid-variants of the variables previously prefixed with `BAK_`
  4. Set the SendGrid event webhook HTTP POST URL to the correct callback server endpoint, with the correct username and password
  5. Deploy the branch on Travis with `STAGING_BRANCH=sendgrid-email-fallback` and `DEPLOY_WORKER=true`
  6. Send an email campaign (using a valid email and `bouncetest@tribulant.com`)
  2. Ensure that the `status` and `error_code` columns of the`email_messages` are updated correctly

## Deploy Notes

**New environment variables**:

- `EMAIL_FALLBACK_ACTIVATE`: Switch to true to use SendGrid as fallback for all emails. Ensure that the SMTP settings are properly configured as well. (worker and backend)

## Todo

- [x] Update the incident response doc to explain about the SendGrid fallback

```
BACKEND_SES_HOST
BACKEND_SES_USER
BACKEND_SES_PASS
WORKER_SES_HOST
WORKER_SES_USER
WORKER_SES_PASS
```

### CODE REVIEW

File: backend/src/email/middlewares/email.middleware.ts [hunk 1]
```diff
@@ -122,10 +122,18 @@ const isFromAddressAccepted = async (
   next: NextFunction
 ): Promise<Response | void> => {
   const { from } = req.body
+  const defaultEmail = config.get('mailFrom')
+
+  if (config.get('emailFallback.activate') && from !== defaultEmail) {
+    return res.set('Retry-After', '3600').status(503).json({
+      message:
+        'Unable to use a custom from address due to downtime. Please try again in 1 hour or use the default from address.',
```
Comment (lamkeewei) [inline backend/src/email/middlewares/email.middleware.ts:130]: "Please try again in 1 hour" seems quite arbitrary since we might not know when the service will be back up again. In addition, conflicting recovery time information might also be in the info banner. This might confuse users. 

Would prefer a more generic message that encourages users to use the default mail from address. Alternatively, I was thinking we might be able to modify `getCustomFromAddress` to only return the default mail from when fallback is activated. This way, users wouldn't even be able to choose their custom from address.

Comment (zwliew) [reply backend/src/email/middlewares/email.middleware.ts]: Thanks for the review! I've changed the message to "Please use the default from address instead.". I've also modified `getCustomFromAddress` like you mentioned.

I think it's still a good idea to keep this condition in `isFromAddressAccepted` though, since API users may end up trying to save templates using the custom from address.

Comment (lamkeewei) [reply backend/src/email/middlewares/email.middleware.ts]: I think we can fallback to the default address for single send. Like you said, they might not have the resource/on-call team to respond.

Comment (zwliew) [reply backend/src/email/middlewares/email.middleware.ts]: I've refactored the rejection of custom from addresses to a separate middleware so that we can apply it only to campaigns and not to single-send messages.

**Comment by miazima** [comment]
We want to log email bounce sub types in email callbacks, here is the relevant pr #1062. Sendgrid provides bounce reasons which can be stored as error sub types too. I have not included this in the pr as we are unable to test the Sendgrid flow right now. 

Here is the previous code written before I reverted the Sendgrid changes.
https://github.com/opengovsg/postmangovsg/blob/c5afd8cc36dbee6e1439f901fbaad5916d21d02f/backend/src/email/utils/callback/parsers/sendgrid.ts

**Comment by zwliew** [comment]
> We want to log email bounce sub types in email callbacks, here is the relevant pr #1062. Sendgrid provides bounce reasons which can be stored as error sub types too. I have not included this in the pr as we are unable to test the Sendgrid flow right now.
> 
> Here is the previous code written before I reverted the Sendgrid changes.
> https://github.com/opengovsg/postmangovsg/blob/c5afd8cc36dbee6e1439f901fbaad5916d21d02f/backend/src/email/utils/callback/parsers/sendgrid.ts

Oh I see, thanks! Since we are unable to test the Sendgrid flow in time, perhaps it should be in a separate PR?

**Comment by lamkeewei** [comment]
**Update** - pending SendGrid account setup before continue on review

File: backend/Dockerfile [hunk 2]
```diff
@@ -2,7 +2,7 @@ FROM node:12-alpine
 
 # required for node-gyp
 RUN apk update && apk upgrade && apk add --no-cache --virtual builds-deps build-base \
-  g++ make python tini
+  g++ make python tini python-dev
```
Comment (zwliew) [inline backend/Dockerfile:5]: I was encountering this build error for workers, and a nearly identical one for backend:
```
Step 4/18 : RUN pip install awscli
 ---> Running in 7e70f6eebdbe
Collecting awscli
  Downloading https://files.pythonhosted.org/packages/69/60/b865ce91eb8965746cc673bc35eac63fe51aed41a757401e1c8bbb6534c9/awscli-1.19.52-py2.py3-none-any.whl (3.6MB)
Collecting colorama<0.4.4,>=0.2.5 (from awscli)
  Downloading https://files.pythonhosted.org/packages/c9/dc/45cdef1b4d119eb96316b3117e6d5708a08029992b2fee2c143c7a0a5cc5/colorama-0.4.3-py2.py3-none-any.whl
Collecting PyYAML<5.5,>=3.10 (from awscli)
  Downloading https://files.pythonhosted.org/packages/a0/a4/d63f2d7597e1a4b55aa3b4d6c5b029991d3b824b5bd331af8d4ab1ed687d/PyYAML-5.4.1.tar.gz (175kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'error'
  Complete output from command /usr/bin/python2 -m pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-mdYr_o --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel Cython:
  Collecting setuptools
    Downloading https://files.pythonhosted.org/packages/e1/b7/182161210a13158cd3ccc41ee19aadef54496b74f2817cc147006ec932b4/setuptools-44.1.1-py2.py3-none-any.whl (583kB)
  Collecting wheel
    Downloading https://files.pythonhosted.org/packages/65/63/39d04c74222770ed1589c0eaba06c05891801219272420b40311cd60c880/wheel-0.36.2-py2.py3-none-any.whl
  Collecting Cython
    Downloading https://files.pythonhosted.org/packages/d9/cd/0d2d90b27219c07f68f1c25bcc7b02dd27639d2180add9d4b73e70945869/Cython-0.29.23.tar.gz (2.1MB)
  Installing collected packages: setuptools, wheel, Cython
    Running setup.py install for Cython: started
      Running setup.py install for Cython: finished with status 'error'
      Complete output from command /usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-gbx66q/Cython/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-T5pUm8/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-mdYr_o --compile:
      Unable to find pgen, not compiling formal grammar.
      running install
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-2.7
      copying cython.py -> build/lib.linux-x86_64-2.7
      creating build/lib.linux-x86_64-2.7/Cython
      copying Cython/Coverage.py -> build/lib.linux-x86_64-2.7/Cython
      copying Cython/Debugging.py -> build/lib.linux-x86_64-2.7/Cython
      copying Cython/StringIOTree.py -> build/lib.linux-x86_64-2.7/Cython
      copying Cython/Shadow.py -> build/lib.linux-x86_64-2.7/Cython
      copying Cython/CodeWriter.py -> build/lib.linux-x86_64-2.7/Cython
      copying Cython/__init__.py -> build/lib.linux-x86_64-2.7/Cython
      copying Cython/TestUtils.py -> build/lib.linux-x86_64-2.7/Cython
      copying Cython/Utils.py -> build/lib.linux-x86_64-2.7/Cython
      creating build/lib.linux-x86_64-2.7/Cython/Build
      copying Cython/Build/Distutils.py -> build/lib.linux-x86_64-2.7/Cython/Build
      copying Cython/Build/IpythonMagic.py -> build/lib.linux-x86_64-2.7/Cython/Build
      copying Cython/Build/Dependencies.py -> build/lib.linux-x86_64-2.7/Cython/Build
      copying Cython/Build/Cythonize.py -> build/lib.linux-x86_64-2.7/Cython/Build
      copying Cython/Build/BuildExecutable.py -> build/lib.linux-x86_64-2.7/Cython/Build
      copying Cython/Build/Inline.py -> build/lib.linux-x86_64-2.7/Cython/Build
      copying Cython/Build/__init__.py -> build/lib.linux-x86_64-2.7/Cython/Build
      creating build/lib.linux-x86_64-2.7/Cython/Compiler
      copying Cython/Compiler/CmdLine.py -> build/lib.linux-x86_64-2.7/Cython/Compiler
      copying Cython/Compiler/TreeFragment.py -> build/lib.linux-x86_64-2.7/Cython/Compiler
      copying Cython/Compiler/Code.py -> build/lib.linux-x86_64-2.7/Cython/Compiler
      copying Cython/Compiler/Symtab.py -> build/lib.linux-x86_64-2.7/Cython/Compiler
      copying Cython/Compiler/CodeGeneration.py -> build/lib.linux-x86_64-2.7/Cython/Compiler
      copying Cython/Compiler/FusedNode.py -> build/lib.linux-x86_64-2.7/Cython/Compiler
      copying Cython/Compiler/Annotate.py -> build/lib.linux-x86_64-2.7/Cython/Compiler
      copying Cython/Compiler/ParseTreeTransforms.py -> build/lib.linux-x86_64-2.7/Cython/Compiler
      copying Cython/Compiler/TypeSlots.py -> build/lib.linux-x86_64-2.7/Cython/Compiler
      copying Cython/Compiler/Pythran.py -> build/lib.linux-x86_64-2.7/Cython/Compiler
      copying Cython/Compiler/Main.py -> build/lib.linux-x86_64-2.7/Cython/Compiler
      copying Cython/Compiler/FlowControl.py -> build/lib.linux-x86_64-2.7/Cython/Compiler
      copying Cython/Compiler/Optimize.py -> build/lib.linux-x86_64-2.7/Cython/Compiler
      copying Cython/Compiler/Nodes.py -> build/lib.linux-x86_64-2.7/Cython/Compiler
      copying Cython/Compiler/Builtin.py -> build/lib.linux-x86_64-2.7/Cython/Compiler
      copying Cython/Compiler/TypeInference.py -> build/lib.linux-x86_64-2.7/Cython/Compiler
      copying Cython/Compiler/Visitor.py -> build/lib.linux-x86_64-2.7/Cython/Compiler
      copying Cython/Compiler/Scanning.py -> build/lib.linux-x86_64-2.7/Cython/Compiler
      copying Cython/Compiler/Lexicon.py -> build/lib.linux-x86_64-2.7/Cython/Compiler
      copying Cython/Compiler/Buffer.py -> build/lib.linux-x86_64-2.7/Cython/Compiler
      copying Cython/Compiler/Interpreter.py -> build/lib.linux-x86_64-2.7/Cython/Compiler
      copying Cython/Compiler/Version.py -> build/lib.linux-x86_64-2.7/Cython/Compiler
      copying Cython/Compiler/Errors.py -> build/lib.linux-x86_64-2.7/Cython/Compiler
      copying Cython/Compiler/AnalysedTreeTransforms.py -> build/lib.linux-x86_64-2.7/Cython/Compiler
      copying Cython/Compiler/TreePath.py -> build/lib.linux-x86_64-2.7/Cython/Compiler
      copying Cython/Compiler/Options.py -> build/lib.linux-x86_64-2.7/Cython/Compiler
      copying Cython/Compiler/DebugFlags.py -> build/lib.linux-x86_64-2.7/Cython/Compiler
      copying Cython/Compiler/ExprNodes.py -> build/lib.linux-x86_64-2.7/Cython/Compiler
      copying Cython/Compiler/__init__.py -> build/lib.linux-x86_64-2.7/Cython/Compiler
      copying Cython/Compiler/Pipeline.py -> build/lib.linux-x86_64-2.7/Cython/Compiler
      copying Cython/Compiler/StringEncoding.py -> build/lib.linux-x86_64-2.7/Cython/Compiler
      copying Cython/Compiler/UtilNodes.py -> build/lib.linux-x86_64-2.7/Cython/Compiler
      copying Cython/Compiler/Future.py -> build/lib.linux-x86_64-2.7/Cython/Compiler
      copying Cython/Compiler/PyrexTypes.py -> build/lib.linux-x86_64-2.7/Cython/Compiler
      copying Cython/Compiler/MemoryView.py -> build/lib.linux-x86_64-2.7/Cython/Compiler
      copying Cython/Compiler/ModuleNode.py -> build/lib.linux-x86_64-2.7/Cython/Compiler
      copying Cython/Compiler/Naming.py -> build/lib.linux-x86_64-2.7/Cython/Compiler
      copying Cython/Compiler/AutoDocTransforms.py -> build/lib.linux-x86_64-2.7/Cython/Compiler
      copying Cython/Compiler/UtilityCode.py -> build/lib.linux-x86_64-2.7/Cython/Compiler
      copying Cython/Compiler/CythonScope.py -> build/lib.linux-x86_64-2.7/Cython/Compiler
      copying Cython/Compiler/Parsing.py -> build/lib.linux-x86_64-2.7/Cython/Compiler
      creating build/lib.linux-x86_64-2.7/Cython/Runtime
      copying Cython/Runtime/__init__.py -> build/lib.linux-x86_64-2.7/Cython/Runtime
      creating build/lib.linux-x86_64-2.7/Cython/Distutils
      copying Cython/Distutils/old_build_ext.py -> build/lib.linux-x86_64-2.7/Cython/Distutils
      copying Cython/Distutils/build_ext.py -> build/lib.linux-x86_64-2.7/Cython/Distutils
      copying Cython/Distutils/extension.py -> build/lib.linux-x86_64-2.7/Cython/Distutils
      copying Cython/Distutils/__init__.py -> build/lib.linux-x86_64-2.7/Cython/Distutils
      creating build/lib.linux-x86_64-2.7/Cython/Debugger
      copying Cython/Debugger/libpython.py -> build/lib.linux-x86_64-2.7/Cython/Debugger
      copying Cython/Debugger/DebugWriter.py -> build/lib.linux-x86_64-2.7/Cython/Debugger
      copying Cython/Debugger/libcython.py -> build/lib.linux-x86_64-2.7/Cython/Debugger
      copying Cython/Debugger/__init__.py -> build/lib.linux-x86_64-2.7/Cython/Debugger
      copying Cython/Debugger/Cygdb.py -> build/lib.linux-x86_64-2.7/Cython/Debugger
      creating build/lib.linux-x86_64-2.7/Cython/Debugger/Tests
      copying Cython/Debugger/Tests/test_libcython_in_gdb.py -> build/lib.linux-x86_64-2.7/Cython/Debugger/Tests
      copying Cython/Debugger/Tests/__init__.py -> build/lib.linux-x86_64-2.7/Cython/Debugger/Tests
      copying Cython/Debugger/Tests/test_libpython_in_gdb.py -> build/lib.linux-x86_64-2.7/Cython/Debugger/Tests
      copying Cython/Debugger/Tests/TestLibCython.py -> build/lib.linux-x86_64-2.7/Cython/Debugger/Tests
      creating build/lib.linux-x86_64-2.7/Cython/Plex
      copying Cython/Plex/Machines.py -> build/lib.linux-x86_64-2.7/Cython/Plex
      copying Cython/Plex/Regexps.py -> build/lib.linux-x86_64-2.7/Cython/Plex
      copying Cython/Plex/Timing.py -> build/lib.linux-x86_64-2.7/Cython/Plex
      copying Cython/Plex/Actions.py -> build/lib.linux-x86_64-2.7/Cython/Plex
      copying Cython/Plex/Traditional.py -> build/lib.linux-x86_64-2.7/Cython/Plex
      copying Cython/Plex/Lexicons.py -> build/lib.linux-x86_64-2.7/Cython/Plex
      copying Cython/Plex/Scanners.py -> build/lib.linux-x86_64-2.7/Cython/Plex
      copying Cython/Plex/Errors.py -> build/lib.linux-x86_64-2.7/Cython/Plex
      copying Cython/Plex/Transitions.py -> build/lib.linux-x86_64-2.7/Cython/Plex
      copying Cython/Plex/__init__.py -> build/lib.linux-x86_64-2.7/Cython/Plex
      copying Cython/Plex/DFA.py -> build/lib.linux-x86_64-2.7/Cython/Plex
      creating build/lib.linux-x86_64-2.7/Cython/Tests
      copying Cython/Tests/TestJediTyper.py -> build/lib.linux-x86_64-2.7/Cython/Tests
      copying Cython/Tests/xmlrunner.py -> build/lib.linux-x86_64-2.7/Cython/Tests
      copying Cython/Tests/TestCythonUtils.py -> build/lib.linux-x86_64-2.7/Cython/Tests
      copying Cython/Tests/TestCodeWriter.py -> build/lib.linux-x86_64-2.7/Cython/Tests
      copying Cython/Tests/__init__.py -> build/lib.linux-x86_64-2.7/Cython/Tests
      copying Cython/Tests/TestStringIOTree.py -> build/lib.linux-x86_64-2.7/Cython/Tests
      creating build/lib.linux-x86_64-2.7/Cython/Build/Tests
      copying Cython/Build/Tests/TestStripLiterals.py -> build/lib.linux-x86_64-2.7/Cython/Build/Tests
      copying Cython/Build/Tests/TestIpythonMagic.py -> build/lib.linux-x86_64-2.7/Cython/Build/Tests
      copying Cython/Build/Tests/TestCyCache.py -> build/lib.linux-x86_64-2.7/Cython/Build/Tests
      copying Cython/Build/Tests/TestInline.py -> build/lib.linux-x86_64-2.7/Cython/Build/Tests
      copying Cython/Build/Tests/__init__.py -> build/lib.linux-x86_64-2.7/Cython/Build/Tests
      creating build/lib.linux-x86_64-2.7/Cython/Compiler/Tests
      copying Cython/Compiler/Tests/TestFlowControl.py -> build/lib.linux-x86_64-2.7/Cython/Compiler/Tests
      copying Cython/Compiler/Tests/TestMemView.py -> build/lib.linux-x86_64-2.7/Cython/Compiler/Tests
      copying Cython/Compiler/Tests/TestTreePath.py -> build/lib.linux-x86_64-2.7/Cython/Compiler/Tests
      copying Cython/Compiler/Tests/TestTreeFragment.py -> build/lib.linux-x86_64-2.7/Cython/Compiler/Tests
      copying Cython/Compiler/Tests/TestTypes.py -> build/lib.linux-x86_64-2.7/Cython/Compiler/Tests
      copying Cython/Compiler/Tests/TestStringEncoding.py -> build/lib.linux-x86_64-2.7/Cython/Compiler/Tests
      copying Cython/Compiler/Tests/TestVisitor.py -> build/lib.linux-x86_64-2.7/Cython/Compiler/Tests
      copying Cython/Compiler/Tests/TestGrammar.py -> build/lib.linux-x86_64-2.7/Cython/Compiler/Tests
      copying Cython/Compiler/Tests/TestSignatureMatching.py -> build/lib.linux-x86_64-2.7/Cython/Compiler/Tests
      copying Cython/Compiler/Tests/TestParseTreeTransforms.py -> build/lib.linux-x86_64-2.7/Cython/Compiler/Tests
      copying Cython/Compiler/Tests/__init__.py -> build/lib.linux-x86_64-2.7/Cython/Compiler/Tests
      copying Cython/Compiler/Tests/TestCmdLine.py -> build/lib.linux-x86_64-2.7/Cython/Compiler/Tests
      copying Cython/Compiler/Tests/TestUtilityLoad.py -> build/lib.linux-x86_64-2.7/Cython/Compiler/Tests
      copying Cython/Compiler/Tests/TestBuffer.py -> build/lib.linux-x86_64-2.7/Cython/Compiler/Tests
      creating build/lib.linux-x86_64-2.7/Cython/Utility
      copying Cython/Utility/__init__.py -> build/lib.linux-x86_64-2.7/Cython/Utility
      creating build/lib.linux-x86_64-2.7/Cython/Tempita
      copying Cython/Tempita/_tempita.py -> build/lib.linux-x86_64-2.7/Cython/Tempita
      copying Cython/Tempita/compat3.py -> build/lib.linux-x86_64-2.7/Cython/Tempita
      copying Cython/Tempita/_looper.py -> build/lib.linux-x86_64-2.7/Cython/Tempita
      copying Cython/Tempita/__init__.py -> build/lib.linux-x86_64-2.7/Cython/Tempita
      creating build/lib.linux-x86_64-2.7/pyximport
      copying pyximport/pyximport.py -> build/lib.linux-x86_64-2.7/pyximport
      copying pyximport/__init__.py -> build/lib.linux-x86_64-2.7/pyximport
      copying pyximport/pyxbuild.py -> build/lib.linux-x86_64-2.7/pyximport
      creating build/lib.linux-x86_64-2.7/Cython/Includes
      copying Cython/Includes/openmp.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes
      creating build/lib.linux-x86_64-2.7/Cython/Includes/libcpp
      copying Cython/Includes/libcpp/iterator.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/libcpp
      copying Cython/Includes/libcpp/vector.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/libcpp
      copying Cython/Includes/libcpp/functional.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/libcpp
      copying Cython/Includes/libcpp/complex.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/libcpp
      copying Cython/Includes/libcpp/forward_list.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/libcpp
      copying Cython/Includes/libcpp/unordered_set.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/libcpp
      copying Cython/Includes/libcpp/algorithm.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/libcpp
      copying Cython/Includes/libcpp/string.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/libcpp
      copying Cython/Includes/libcpp/typeinfo.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/libcpp
      copying Cython/Includes/libcpp/set.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/libcpp
      copying Cython/Includes/libcpp/cast.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/libcpp
      copying Cython/Includes/libcpp/memory.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/libcpp
      copying Cython/Includes/libcpp/deque.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/libcpp
      copying Cython/Includes/libcpp/utility.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/libcpp
      copying Cython/Includes/libcpp/limits.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/libcpp
      copying Cython/Includes/libcpp/stack.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/libcpp
      copying Cython/Includes/libcpp/typeindex.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/libcpp
      copying Cython/Includes/libcpp/unordered_map.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/libcpp
      copying Cython/Includes/libcpp/queue.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/libcpp
      copying Cython/Includes/libcpp/list.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/libcpp
      copying Cython/Includes/libcpp/pair.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/libcpp
      copying Cython/Includes/libcpp/__init__.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/libcpp
      copying Cython/Includes/libcpp/map.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/libcpp
      creating build/lib.linux-x86_64-2.7/Cython/Includes/posix
      copying Cython/Includes/posix/resource.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/posix
      copying Cython/Includes/posix/wait.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/posix
      copying Cython/Includes/posix/ioctl.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/posix
      copying Cython/Includes/posix/mman.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/posix
      copying Cython/Includes/posix/dlfcn.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/posix
      copying Cython/Includes/posix/types.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/posix
      copying Cython/Includes/posix/time.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/posix
      copying Cython/Includes/posix/stat.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/posix
      copying Cython/Includes/posix/signal.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/posix
      copying Cython/Includes/posix/select.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/posix
      copying Cython/Includes/posix/fcntl.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/posix
      copying Cython/Includes/posix/strings.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/posix
      copying Cython/Includes/posix/__init__.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/posix
      copying Cython/Includes/posix/unistd.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/posix
      copying Cython/Includes/posix/stdlib.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/posix
      copying Cython/Includes/posix/stdio.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/posix
      creating build/lib.linux-x86_64-2.7/Cython/Includes/numpy
      copying Cython/Includes/numpy/math.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/numpy
      copying Cython/Includes/numpy/__init__.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/numpy
      creating build/lib.linux-x86_64-2.7/Cython/Includes/Deprecated
      copying Cython/Includes/Deprecated/python_exc.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/Deprecated
      copying Cython/Includes/Deprecated/python_version.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/Deprecated
      copying Cython/Includes/Deprecated/python_type.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/Deprecated
      copying Cython/Includes/Deprecated/python_method.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/Deprecated
      copying Cython/Includes/Deprecated/python_oldbuffer.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/Deprecated
      copying Cython/Includes/Deprecated/python_string.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/Deprecated
      copying Cython/Includes/Deprecated/python_module.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/Deprecated
      copying Cython/Includes/Deprecated/python_set.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/Deprecated
      copying Cython/Includes/Deprecated/python_long.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/Deprecated
      copying Cython/Includes/Deprecated/python_weakref.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/Deprecated
      copying Cython/Includes/Deprecated/python_ref.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/Deprecated
      copying Cython/Includes/Deprecated/python_unicode.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/Deprecated
      copying Cython/Includes/Deprecated/python_function.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/Deprecated
      copying Cython/Includes/Deprecated/python_number.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/Deprecated
      copying Cython/Includes/Deprecated/python_instance.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/Deprecated
      copying Cython/Includes/Deprecated/python_buffer.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/Deprecated
      copying Cython/Includes/Deprecated/python_sequence.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/Deprecated
      copying Cython/Includes/Deprecated/python_cobject.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/Deprecated
      copying Cython/Includes/Deprecated/python_int.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/Deprecated
      copying Cython/Includes/Deprecated/python_bytes.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/Deprecated
      copying Cython/Includes/Deprecated/python_complex.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/Deprecated
      copying Cython/Includes/Deprecated/python_pycapsule.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/Deprecated
      copying Cython/Includes/Deprecated/python_tuple.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/Deprecated
      copying Cython/Includes/Deprecated/python_object.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/Deprecated
      copying Cython/Includes/Deprecated/python_float.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/Deprecated
      copying Cython/Includes/Deprecated/python_iterator.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/Deprecated
      copying Cython/Includes/Deprecated/python_bool.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/Deprecated
      copying Cython/Includes/Deprecated/python_dict.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/Deprecated
      copying Cython/Includes/Deprecated/python_mapping.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/Deprecated
      copying Cython/Includes/Deprecated/python.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/Deprecated
      copying Cython/Includes/Deprecated/python_getargs.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/Deprecated
      copying Cython/Includes/Deprecated/stdlib.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/Deprecated
      copying Cython/Includes/Deprecated/python_mem.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/Deprecated
      copying Cython/Includes/Deprecated/stdio.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/Deprecated
      copying Cython/Includes/Deprecated/python_list.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/Deprecated
      copying Cython/Includes/Deprecated/stl.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/Deprecated
      creating build/lib.linux-x86_64-2.7/Cython/Includes/libc
      copying Cython/Includes/libc/errno.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/libc
      copying Cython/Includes/libc/setjmp.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/libc
      copying Cython/Includes/libc/string.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/libc
      copying Cython/Includes/libc/time.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/libc
      copying Cython/Includes/libc/locale.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/libc
      copying Cython/Includes/libc/float.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/libc
      copying Cython/Includes/libc/signal.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/libc
      copying Cython/Includes/libc/limits.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/libc
      copying Cython/Includes/libc/math.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/libc
      copying Cython/Includes/libc/stdint.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/libc
      copying Cython/Includes/libc/stddef.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/libc
      copying Cython/Includes/libc/__init__.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/libc
      copying Cython/Includes/libc/stdlib.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/libc
      copying Cython/Includes/libc/stdio.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/libc
      creating build/lib.linux-x86_64-2.7/Cython/Includes/cpython
      copying Cython/Includes/cpython/iterator.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/cpython
      copying Cython/Includes/cpython/exc.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/cpython
      copying Cython/Includes/cpython/number.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/cpython
      copying Cython/Includes/cpython/slice.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/cpython
      copying Cython/Includes/cpython/int.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/cpython
      copying Cython/Includes/cpython/method.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/cpython
      copying Cython/Includes/cpython/type.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/cpython
      copying Cython/Includes/cpython/complex.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/cpython
      copying Cython/Includes/cpython/conversion.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/cpython
      copying Cython/Includes/cpython/pystate.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/cpython
      copying Cython/Includes/cpython/bool.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/cpython
      copying Cython/Includes/cpython/string.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/cpython
      copying Cython/Includes/cpython/iterobject.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/cpython
      copying Cython/Includes/cpython/unicode.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/cpython
      copying Cython/Includes/cpython/long.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/cpython
      copying Cython/Includes/cpython/set.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/cpython
      copying Cython/Includes/cpython/version.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/cpython
      copying Cython/Includes/cpython/instance.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/cpython
      copying Cython/Includes/cpython/pythread.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/cpython
      copying Cython/Includes/cpython/mapping.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/cpython
      copying Cython/Includes/cpython/memoryview.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/cpython
      copying Cython/Includes/cpython/float.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/cpython
      copying Cython/Includes/cpython/oldbuffer.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/cpython
      copying Cython/Includes/cpython/sequence.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/cpython
      copying Cython/Includes/cpython/codecs.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/cpython
      copying Cython/Includes/cpython/bytes.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/cpython
      copying Cython/Includes/cpython/mem.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/cpython
      copying Cython/Includes/cpython/bytearray.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/cpython
      copying Cython/Includes/cpython/ceval.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/cpython
      copying Cython/Includes/cpython/object.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/cpython
      copying Cython/Includes/cpython/longintrepr.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/cpython
      copying Cython/Includes/cpython/cellobject.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/cpython
      copying Cython/Includes/cpython/weakref.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/cpython
      copying Cython/Includes/cpython/cobject.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/cpython
      copying Cython/Includes/cpython/dict.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/cpython
      copying Cython/Includes/cpython/module.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/cpython
      copying Cython/Includes/cpython/function.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/cpython
      copying Cython/Includes/cpython/list.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/cpython
      copying Cython/Includes/cpython/ref.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/cpython
      copying Cython/Includes/cpython/getargs.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/cpython
      copying Cython/Includes/cpython/pylifecycle.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/cpython
      copying Cython/Includes/cpython/pycapsule.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/cpython
      copying Cython/Includes/cpython/tuple.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/cpython
      copying Cython/Includes/cpython/array.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/cpython
      copying Cython/Includes/cpython/datetime.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/cpython
      copying Cython/Includes/cpython/__init__.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/cpython
      copying Cython/Includes/cpython/genobject.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/cpython
      copying Cython/Includes/cpython/buffer.pxd -> build/lib.linux-x86_64-2.7/Cython/Includes/cpython
      copying Cython/Compiler/Visitor.pxd -> build/lib.linux-x86_64-2.7/Cython/Compiler
      copying Cython/Compiler/Parsing.pxd -> build/lib.linux-x86_64-2.7/Cython/Compiler
      copying Cython/Compiler/Scanning.pxd -> build/lib.linux-x86_64-2.7/Cython/Compiler
      copying Cython/Compiler/Code.pxd -> build/lib.linux-x86_64-2.7/Cython/Compiler
      copying Cython/Compiler/FlowControl.pxd -> build/lib.linux-x86_64-2.7/Cython/Compiler
      copying Cython/Compiler/ParseTreeTransforms.pxd -> build/lib.linux-x86_64-2.7/Cython/Compiler
      copying Cython/Runtime/refnanny.pyx -> build/lib.linux-x86_64-2.7/Cython/Runtime
      copying Cython/Debugger/Tests/codefile -> build/lib.linux-x86_64-2.7/Cython/Debugger/Tests
      copying Cython/Debugger/Tests/cfuncs.c -> build/lib.linux-x86_64-2.7/Cython/Debugger/Tests
      copying Cython/Plex/Actions.pxd -> build/lib.linux-x86_64-2.7/Cython/Plex
      copying Cython/Plex/Scanners.pxd -> build/lib.linux-x86_64-2.7/Cython/Plex
      copying Cython/Utility/TestCyUtilityLoader.pyx -> build/lib.linux-x86_64-2.7/Cython/Utility
      copying Cython/Utility/CConvert.pyx -> build/lib.linux-x86_64-2.7/Cython/Utility
      copying Cython/Utility/MemoryView.pyx -> build/lib.linux-x86_64-2.7/Cython/Utility
      copying Cython/Utility/CppConvert.pyx -> build/lib.linux-x86_64-2.7/Cython/Utility
      copying Cython/Utility/TestCythonScope.pyx -> build/lib.linux-x86_64-2.7/Cython/Utility
      copying Cython/Utility/CpdefEnums.pyx -> build/lib.linux-x86_64-2.7/Cython/Utility
      copying Cython/Utility/TestUtilityLoader.c -> build/lib.linux-x86_64-2.7/Cython/Utility
      copying Cython/Utility/MemoryView_C.c -> build/lib.linux-x86_64-2.7/Cython/Utility
      copying Cython/Utility/Coroutine.c -> build/lib.linux-x86_64-2.7/Cython/Utility
      copying Cython/Utility/CythonFunction.c -> build/lib.linux-x86_64-2.7/Cython/Utility
      copying Cython/Utility/AsyncGen.c -> build/lib.linux-x86_64-2.7/Cython/Utility
      copying Cython/Utility/Printing.c -> build/lib.linux-x86_64-2.7/Cython/Utility
      copying Cython/Utility/Embed.c -> build/lib.linux-x86_64-2.7/Cython/Utility
      copying Cython/Utility/StringTools.c -> build/lib.linux-x86_64-2.7/Cython/Utility
      copying Cython/Utility/Builtins.c -> build/lib.linux-x86_64-2.7/Cython/Utility
      copying Cython/Utility/ImportExport.c -> build/lib.linux-x86_64-2.7/Cython/Utility
      copying Cython/Utility/Complex.c -> build/lib.linux-x86_64-2.7/Cython/Utility
      copying Cython/Utility/Exceptions.c -> build/lib.linux-x86_64-2.7/Cython/Utility
      copying Cython/Utility/Optimize.c -> build/lib.linux-x86_64-2.7/Cython/Utility
      copying Cython/Utility/ObjectHandling.c -> build/lib.linux-x86_64-2.7/Cython/Utility
      copying Cython/Utility/CMath.c -> build/lib.linux-x86_64-2.7/Cython/Utility
      copying Cython/Utility/CommonStructures.c -> build/lib.linux-x86_64-2.7/Cython/Utility
      copying Cython/Utility/TypeConversion.c -> build/lib.linux-x86_64-2.7/Cython/Utility
      copying Cython/Utility/FunctionArguments.c -> build/lib.linux-x86_64-2.7/Cython/Utility
      copying Cython/Utility/Profile.c -> build/lib.linux-x86_64-2.7/Cython/Utility
      copying Cython/Utility/ModuleSetupCode.c -> build/lib.linux-x86_64-2.7/Cython/Utility
      copying Cython/Utility/Overflow.c -> build/lib.linux-x86_64-2.7/Cython/Utility
      copying Cython/Utility/ExtensionTypes.c -> build/lib.linux-x86_64-2.7/Cython/Utility
      copying Cython/Utility/Capsule.c -> build/lib.linux-x86_64-2.7/Cython/Utility
      copying Cython/Utility/Buffer.c -> build/lib.linux-x86_64-2.7/Cython/Utility
      copying Cython/Utility/arrayarray.h -> build/lib.linux-x86_64-2.7/Cython/Utility
      copying Cython/Utility/CppSupport.cpp -> build/lib.linux-x86_64-2.7/Cython/Utility
      running build_ext
      building 'Cython.Plex.Scanners' extension
      creating build/temp.linux-x86_64-2.7
      creating build/temp.linux-x86_64-2.7/tmp
      creating build/temp.linux-x86_64-2.7/tmp/pip-install-gbx66q
      creating build/temp.linux-x86_64-2.7/tmp/pip-install-gbx66q/Cython
      creating build/temp.linux-x86_64-2.7/tmp/pip-install-gbx66q/Cython/Cython
      creating build/temp.linux-x86_64-2.7/tmp/pip-install-gbx66q/Cython/Cython/Plex
      gcc -fno-strict-aliasing -Os -fomit-frame-pointer -g -DNDEBUG -Os -fomit-frame-pointer -g -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/include/python2.7 -c /tmp/pip-install-gbx66q/Cython/Cython/Plex/Scanners.c -o build/temp.linux-x86_64-2.7/tmp/pip-install-gbx66q/Cython/Cython/Plex/Scanners.o
      /tmp/pip-install-gbx66q/Cython/Cython/Plex/Scanners.c:21:10: fatal error: Python.h: No such file or directory
         21 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      error: command 'gcc' failed with exit status 1
  
      ----------------------------------------
  Command "/usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-gbx66q/Cython/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-T5pUm8/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-mdYr_o --compile" failed with error code 1 in /tmp/pip-install-gbx66q/Cython/
  
  ----------------------------------------
Command "/usr/bin/python2 -m pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-mdYr_o --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel Cython" failed with error code 1 in None
The command '/bin/sh -c pip install awscli' returned a non-zero code: 1
```

Comment (lamkeewei) [reply backend/Dockerfile:5]: Were these errors only recently introduced in this PR?

Comment (zwliew) [reply backend/Dockerfile:5]: I'm not sure. It didn't occur when I was testing it yesterday but suddenly occured when I reran a job today (even without changing any code).

Comment (zwliew) [reply backend/Dockerfile:5]: I'll try looking further into it.

File: backend/src/core/loaders/express.loader.ts [hunk 3]
```diff
@@ -91,6 +91,13 @@ const expressApp = ({ app }: { app: express.Application }): void => {
   app.use(requestTracerMiddleware)
 
   app.use(overrideContentTypeHeaderMiddleware)
+
+  // We need to parse the body as text specifically for SendGrid callbacks.
+  // This is to avoid stripping whitespace characters and messing with unicode encoding.
+  // This route affects SES callbacks as well, so we'll need to parse the text as JSON
+  // in the parseEvent() handle before parsing the SES event.
+  app.use('/v1/callback/email', bodyParser.text({ type: 'application/json' }))
```
Comment (zwliew) [inline backend/src/core/loaders/express.loader.ts:99]: SendGrid events contain carriage return and newline characters (`\r\n`) and some even have unicode-encoded characters. The JSON body-parser strips the newline characters and decodes the unicode characters.

I had a less intrusive fix here: https://github.com/opengovsg/postmangovsg/pull/1026/commits/201d0f4729e6b9a032b5f957b7fd0d48d4ee3ecc
But, I think it's not great for reasons stated in the revert: https://github.com/opengovsg/postmangovsg/pull/1026/commits/5473c72307c46a6e1195bda03eead2cbd8d0f28e

I ended up with this solution since it isn't super intrusive, but it does affect the SES callbacks as well.  One other solution is to split the SES and SendGrid callback endpoints.

File: backend/Dockerfile (hunk 2 above)
Comment (lamkeewei) [reply backend/Dockerfile]: Seems like an issue that occured with installation of `aws-cli`. Maybe we didn't hit this issue previously as this layer in the Docker image is cached.

File: backend/src/email/utils/callback/parsers/sendgrid.ts [hunk 4]
```diff
@@ -29,19 +29,14 @@ type SendgridRecord = {
...
-
 const isEvent = (req: Request): boolean => {
   const signature = req.get(SIGNATURE_HEADER)
   const timestamp = req.get(TIMESTAMP_HEADER)
   if (!(signature && timestamp && req.body)) {
     return false
   }
   const decodedSignature = Signature.fromBase64(signature)
-  const timestampPayload = timestamp + stringifyPayload(req.body)
+  const timestampPayload = timestamp + req.body
```
Comment (zwliew) [inline backend/src/email/utils/callback/parsers/sendgrid.ts]: The JSON body-parser causes `req.body` to be a JSON object, but we need it to be the `string` that was sent in the callback request in its original form, including any `\r\n` characters.

File: backend/Dockerfile (hunk 2 above)
Comment (zwliew) [reply backend/Dockerfile:5]: Yeah, maybe an update to `aws-cli` caused it? I think there isn't any issue with installing `python-dev`.

File: backend/src/email/utils/callback/parsers/sendgrid.ts (hunk 4 above)
Comment (zwliew) [reply backend/src/email/utils/callback/parsers/sendgrid.ts]: Here's an example from the official SendGrid samples: https://github.com/sendgrid/sendgrid-nodejs/commit/8110b173007049836455198450947780e9a70416

File: backend/src/email/middlewares/email.middleware.ts [hunk 5]
```diff
@@ -241,18 +270,20 @@ const getCustomFromAddress = async (
...
-  const result = []
+  const result = [defaultEmail]
 
-  try {
-    const fromAddress = await CustomDomainService.getCustomFromAddress(email)
-    if (fromAddress) result.push(fromAddress)
-    result.push(defaultEmail)
-  } catch (err) {
-    return next(err)
+  if (!config.get('emailFallback.activate')) {
```
Comment (lamkeewei) [inline backend/src/email/middlewares/email.middleware.ts:276]: One side effect of this is that when email fallback is activated, the email section in the settings tab will be reverted back to the request form (like when they don't have a custom from registered). 

Rather than not returning the custom from address as an option, would it be better to just rely on the error returned when the `PUT` call is made.

Comment (zwliew) [reply backend/src/email/middlewares/email.middleware.ts:276]: Sounds good

File: backend/src/core/loaders/express.loader.ts (hunk 3 above)
Comment (lamkeewei) [reply backend/src/core/loaders/express.loader.ts:99]: I think this is fine. I've checked and [only one](https://github.com/expressjs/body-parser/blob/480b1cfe29af19c070f4ae96e0d598c099f42a12/lib/types/json.js#L99) `body-parser` middleware will run each time.

**Review by lamkeewei — APPROVED** [review]
lgtm! Tested the following and works as expected:
1. Activation of email fallback should prevent verifying new custom from address
2. Activation of email fallback should prevent usage of custom from address
3. SendGrid events are parsed and handled correctly
4. SES events are parsed and handled correctly
5. Sendgrid is able to deliver to SGMail email addresses
