### PR TITLE
style: Fixes for colours, typography, buttons, campaign table and others

### LINKED ISSUE #760: Updated color codes
Color codes have been updated to pass accessibility tests. New colors have been added, and color style Primary/Coral has been changed to Error/Fire Red. Please check new color codes against existing components.

Please refer to [slide 3: Colors](https://docs.google.com/presentation/d/1gk4npC6zRzw3OQjykm1QB5loQ0v-x2q4tRxBcuJ29tg/edit?usp=sharing) for more notes on changes. Our updated color guide can also be viewed in [figma](https://www.figma.com/file/Wd6jTqpdaqaItVLoyk1Me2/%F0%9F%8E%A8Postman-Design-System?node-id=3559%3A1).

### LINKED ISSUE #761: Updated text styles & typography fixes
Text styles have been updated to follow the 8pt grid system. Please refer to the figma file for the comprehensive guide. We've also noted some wrongly used text styles for specific copies.

Please refer to [slides 4-7: Typography](https://docs.google.com/presentation/d/1gk4npC6zRzw3OQjykm1QB5loQ0v-x2q4tRxBcuJ29tg/edit?usp=sharing) for notes on changes. Our updated typography guidelines can also be viewed in [Figma](https://www.figma.com/file/Wd6jTqpdaqaItVLoyk1Me2/%F0%9F%8E%A8Postman-Design-System?node-id=3562%3A73).

### LINKED ISSUE #762: Button fixes
We've updated the buttons to follow the 8-pt grid system. Buttons are the wrong height, some have the wrong text style, and icons and spacing are the wrong size. 

Please refer to [slide 8-15: buttons](https://docs.google.com/presentation/d/1gk4npC6zRzw3OQjykm1QB5loQ0v-x2q4tRxBcuJ29tg/edit?usp=sharing) for more notes on changes. Our updated button guide can also be viewed in [Figma](https://www.figma.com/file/Wd6jTqpdaqaItVLoyk1Me2/%F0%9F%8E%A8Postman-Design-System?node-id=3573%3A260).

### LINKED ISSUE #764: Campaign Table fixes
Please refer to [slide 22-25: Campaign Table](https://docs.google.com/presentation/d/1gk4npC6zRzw3OQjykm1QB5loQ0v-x2q4tRxBcuJ29tg/edit?usp=sharing) for more notes on fixes.

### LINKED ISSUE #765: Progress Table fixes
Please refer to [slide 26-27: Progress Table](https://docs.google.com/presentation/d/1gk4npC6zRzw3OQjykm1QB5loQ0v-x2q4tRxBcuJ29tg/edit?usp=sharing) for more notes on fixes.

### LINKED ISSUE #766: Sidebar fixes
Please refer to [slide 28: Sidebar](https://docs.google.com/presentation/d/1gk4npC6zRzw3OQjykm1QB5loQ0v-x2q4tRxBcuJ29tg/edit?usp=sharing) for more notes on fixes.

### LINKED ISSUE #767: Toast fixes
Please refer to [slide 29: Toasts](https://docs.google.com/presentation/d/1gk4npC6zRzw3OQjykm1QB5loQ0v-x2q4tRxBcuJ29tg/edit?usp=sharing) for more notes on fixes.

### LINKED ISSUE #768: Pagination fixes
Please refer to [slide 30: Pagination](https://docs.google.com/presentation/d/1gk4npC6zRzw3OQjykm1QB5loQ0v-x2q4tRxBcuJ29tg/edit?usp=sharing) for more notes on fixes.

### LINKED ISSUE #770: Creation Screens layout fixes
Please refer to [slide 33-35: Creation screens](https://docs.google.com/presentation/d/1gk4npC6zRzw3OQjykm1QB5loQ0v-x2q4tRxBcuJ29tg/edit?usp=sharing) for more notes on fixes.

### LINKED ISSUE #771: Modal fixes
Please refer to [slide 36: Modals](https://docs.google.com/presentation/d/1gk4npC6zRzw3OQjykm1QB5loQ0v-x2q4tRxBcuJ29tg/edit?usp=sharing) for more notes on fixes.

### PR DESCRIPTION
**Pull request by lamkeewei**
## Problem

Closes #760 
Closes #761 
Closes #762 
Closes #764 
Closes #765  
Closes #766 
Closes #767 
Closes #768 
Closes #770 
Closes #771 

## Solution

- Updated CSS styles using variables for colours, spacing and heights
- Use placeholder selectors and extend for static classes to [prevent repeated styles](https://medium.com/stories-from-the-keen/when-to-use-extends-vs-mixins-in-sass-b09d55abd53).
- Introduce the following new presentational components:
   - `ButtonGroup` - Use to group multiple buttons together (e.g. previous and next buttons)
   - `StepHeader` - Header for each creation step. Applies consistent spacing for subtitle, title and description text (if any).
   - `StepSection` - Use to group sections in a given step. Apply consistent spacing based on design system. `2rem` between elements in each section and `3rem` between sections.

## Tests
Currently hosted on https://uifixes.postman.gov.sg.

Refer to [UI review slides](https://docs.google.com/presentation/d/1gk4npC6zRzw3OQjykm1QB5loQ0v-x2q4tRxBcuJ29tg/edit?usp=sharing).

- Update colour scheme (Slide 3)
- Typography (Slide 4 - 7)
- Buttons (Slide 8 - 15)
- Campaign table (Slide 22 - 25)
- Progress table (Slide 26 - 27)
- Side bar (Slide 27)
- Toast (Slide 28)
- Pagination (Slide 29)
- Creation pages (Slide 32 - 34)
- Modal (Slide 35)

### CODE REVIEW

**Comment by lamkeewei** [comment]
Putting this back into draft while I also include the fixes for all the remaining UI fixes

File: frontend/src/components/common/cred-label-input/CredLabelInput.tsx [hunk 1]
```diff
@@ -23,7 +24,7 @@ const CredLabelInput = ({
 
   return (
     <>
-      <h5>Credential Label</h5>
+      <LabelWithExternalLink label="Credential Label" />
```
Comment (jeantanzj) [inline frontend/src/components/common/cred-label-input/CredLabelInput.tsx:27]: But there is no external link?

File: frontend/src/styles/app.scss [hunk 2]
```diff
@@ -109,7 +109,7 @@ sub {
 }
 
 .separator {
-  border-bottom: 1px solid $transparent-blue;
+  border-bottom: 1px solid adjust-color($primary-light, $alpha: -0.5);
```
Comment (jeantanzj) [inline frontend/src/styles/app.scss:113]: Should we be changing this to one of the colors in the design scheme instead of changing the color using opacity?

Comment (lamkeewei) [reply frontend/src/styles/app.scss:113]: Wanted to do that at first. But the design system uses opacity instead, so I followed for consistency. 

image

File: frontend/src/components/dashboard/campaigns/Campaigns.tsx [hunk 3]
```diff
@@ -84,15 +84,15 @@ const Campaigns = () => {
     {
       name: 'Created At',
       render: (campaign: Campaign) => (
-        <Moment format="LLL">{campaign.createdAt}</Moment>
+        <Moment format="MMM DD YYYY, HH:mm">{campaign.createdAt}</Moment>
```
Comment (jeantanzj) [inline frontend/src/components/dashboard/campaigns/Campaigns.tsx:89]: Probably need to change the other functions that use 'LLL' as well, for consistency eg
https://github.com/opengovsg/postmangovsg/blob/8e5d63030bfc1bcfdb1dc71878feeee208358c63/frontend/src/components/common/export-recipients/ExportRecipients.tsx#L81 
https://github.com/opengovsg/postmangovsg/blob/8e5d63030bfc1bcfdb1dc71878feeee208358c63/frontend/src/classes/Campaign.ts#L98

File: frontend/src/components/dashboard/settings/custom-from-address/CustomFromAddress.module.scss [hunk 4]
```diff
@@ -28,15 +29,12 @@
...
-      border: 1px solid $primary;
-      color: $primary;
-      &:hover {
-        background: $neutral-light;
-      }
+      @extend %outline-btn;
     }
     .request {
-      @include button($secondary) @include mobile() {
+      @extend %secondary-btn;
```
Comment (jeantanzj) [inline frontend/src/components/dashboard/settings/custom-from-address/CustomFromAddress.module.scss:37]: How do we decide when to use `@include button(...) `vs `@extend`

File: frontend/src/components/dashboard/settings/add-credential-modal/AddCredentialModal.tsx [hunk 5]
```diff
@@ -146,14 +146,24 @@ const AddCredentialModal = ({
...
-        <NextButton
-          onClick={nextFunc}
-          loadingPlaceholder={
-            <>
-              Validating<i className="bx bx-loader-alt bx-spin"></i>
-            </>
-          }
-        />
+        <div className={styles.actionButtons}>
+          <PrimaryButton
```
Comment (jeantanzj) [inline frontend/src/components/dashboard/settings/add-credential-modal/AddCredentialModal.tsx:150]: So when do we use a NextButton instead of PrimaryButton?

File: frontend/src/components/dashboard/settings/custom-from-address/CustomFromAddress.module.scss (hunk 4 above)
Comment (lamkeewei) [reply frontend/src/components/dashboard/settings/custom-from-address/CustomFromAddress.module.scss:37]: Mixins duplicate styles while extend doesn't. Generally if we just want to reuse static styles, we should try to use `@extend` instead of `@include` to reduce the size of the generated CSS.

**Using mixins:** 
```sass
@mixin button($background-color) {
    background-color: $background-color
}

.button-mixin-1 {
    @include button(red)
}

.button-mixin-2 {
    @include button(red)
}
```

Compiles to:
```css
.button-mixin-1 {
  background-color: red;
}

.button-mixin-2 {
  background-color: red;
}
```

**Using extends:**
```sass
%button {
    background-color: red
}

.button-extend-1 {
    @extend %button
}

.button-extend-2 {
    @extend %button
}
```

Compiles to:
```css
.button-extend-2, .button-extend-1 {
  background-color: red;
}
```

**Reference**
- [When to use extends vs mixins](https://medium.com/stories-from-the-keen/when-to-use-extends-vs-mixins-in-sass-b09d55abd53)
- https://www.sassmeister.com/ to test out

File: frontend/src/components/common/modal/Modal.tsx [hunk 6]
```diff
@@ -6,9 +7,11 @@ import styles from './Modal.module.scss'
 const Modal = ({
   onClose,
   children,
+  contentClassName,
```
Comment (jeantanzj) [inline frontend/src/components/common/modal/Modal.tsx:10]: This doesn't actually seem to be used?
And shouldnt the styles on the content be applied on the children directly?
eg 
```tsx
modal.setModalContent(<CreateModal className={contentClassName} name={selectedName} channelType={selectedChannel} />)

// CreateModal
const CreateModal = ({className, name, channelType}...)=> {

return (<div className={cx(styles.section, className)}>...</div>)
}
```

File: frontend/src/components/dashboard/settings/custom-from-address/CustomFromAddress.module.scss (hunk 4 above)
Comment (jeantanzj) [reply frontend/src/components/dashboard/settings/custom-from-address/CustomFromAddress.module.scss:37]: I see.  Ok, good to know! Thanks

```scss
@mixin button($background-color) {
    background-color: $background-color
}

%secondary-btn {
    @include button(#FFF);
}

.ext-1 {
    @extend %secondary-btn
}

.ext-2 {
    @extend %secondary-btn
}

.inc-1 {
    @include button(#FFF);
}

.inc-2 {
    @include button(#FFF);
}
```
compiles to
```css
.ext-2, .ext-1 {
  background-color: #FFF;
}

.inc-1 {
  background-color: #FFF;
}

.inc-2 {
  background-color: #FFF;
}
```

File: frontend/src/components/dashboard/settings/add-credential-modal/AddCredentialModal.tsx (hunk 5 above)
Comment (lamkeewei) [reply frontend/src/components/dashboard/settings/add-credential-modal/AddCredentialModal.tsx:150]: NextButton is mainly a convenience component with a default style (`progress-button`) and button text (Next ->). It's mostly just used in the campaign creation flow. I think apart from the campaign creation flow, we should just directly use PrimaryButton. Haven't done a very thorough comb through to ensure this is consistent though.

**Comment by jeantanzj** [comment]
Are these also supposed to be refactored using StepHeader? 
Screenshot 2020-11-04 at 1 27 08 PM
Screenshot 2020-11-04 at 1 26 49 PM

**Review by jeantanzj — APPROVED** [review]

File: frontend/src/components/common/modal/Modal.tsx (hunk 6 above)
Comment (lamkeewei) [reply frontend/src/components/common/modal/Modal.tsx:10]: Yeah this one's kinda hacky. I had to add this because the CreateModal is the only modal that uses a non-standard padding/width. The issues lies in where the Modal's padding is applied:

```jsx
<div
   id={modalBackgroundId}
   className={styles.modalBg}
   onClick={handleClickBackground}
>
   <div className={styles.modal}>
      <CloseButton onClick={onClose} className={styles.close} />
      <div className={cx(styles.content, contentClassName)}>{children}</div>
   </div>
</div>
```

The padding is applied on the `div` wrapping `{children}`. So applying the padding to the children can only increase the default padding (by adding more padding to the children) but not decrease it, which is what we need. 

Alternative is to get rid of the `div` wrapping the content and have each Modal implement their own padding. But felt that was too big of a change for one exception case though.

**Comment by lamkeewei** [comment]
> Are these also supposed to be refactored using StepHeader?
> Screenshot 2020-11-04 at 1 27 08 PM
> Screenshot 2020-11-04 at 1 26 49 PM

Ah I missed out checking the Details page. Will check through and refactor.
