### PR TITLE
fix: Remove empty rows with tags

### LINKED ISSUE #857: Empty Spacing for Password-protected Page Persists
**Describe the bug**
The checkbox in the password-protected campaign for the removal of empty spaces should remove spacing from empty excel cells when the private content is rendered on the browser. 

Two places where this bug was found:
1. Preview box for Message B
127174160_214803056902270_8472513590533795042_n

2. Password-protected content after entering the password (see pdf sent in slack)

**To Reproduce**
` <b>Staff name:</b> {{name}} <b>Employee Number/NRIC No:</b> {{ee_no}} / {{nric}} </br> <h1>CPF Board Payslip for the Month of {{month}}</h1> <hr> <h2>Earnings for {{month}} {{year}}</h2> <b>{{9001_desc}}</b> {{9001_value}} <b>{{9002_desc}}</b> {{9002_value}} <b>Gross Salary:</b> {{gross_salary}} </br> <b>{{9101_desc}}</b> {{9101_value}} <b>{{9102_desc}}</b> {{9102_value}} <b>Total Salary:</b> {{total_salary}} </br> <b>{{599_desc}}</b> {{599_amt}} <b>{{307_desc}}</b> {{307_amt}} </br> <h2>Grand Total:</h2> {{grand_total}} </br> <hr> <h2>Deduction for {{date}}</h2> <b>{{305_desc}}</b> {{305_amt}} <b>{{370_desc}}</b> {{370_amt}} <b>{{374_desc}}</b> {{374_amt}} </br> <h2>Total Deduction:</h2>{{total_deduction}}`

csv file sent in slack.

**Expected behavior**
The empty spaces should have been removed. 

**Tablet (please complete the following information):**
iPad Pro, Safari

### PR DESCRIPTION
**Pull request by lamkeewei**
## Problem

Closes #857 

## Solution

**Features**:
- Query and remove all `:empty` tags, except for `img`, `br` and `hr`. 

**Improvements**:
- Updated table styles to standardise column sizes

## Tests
Branch is currently hosted at https://emptylines.postman.gov.sg. Apart from running the unit tests, you may also test out the following scenarios. 

Use the following recipient list for the tests:
```
recipient,password,value1
test@test.com,1111,
```

**Nested tags**
Create protected email campaign with the following template. Make sure to check remove empty lines option.
```
<b><i>{{value1}}</i></b>{{value1}}
<b><i>{{value1}}</i></b>{{value1}}
<b><i>{{value1}}</i></b>{{value1}}
<b><i>{{value1}}</i></b>{{value1}}
hello
```
First four rows should be collapsed to 1 `<br />`. 

**Empty table rows**
Create protected email campaign with the following template.
```
<table>
<tr>
<td><b>{{value1}}</b></td>
<td>{{value1}}</td>
</tr>
<tr>
<td><b>recipient</b></td>
<td>{{recipient}}</td>
</tr>
</table>
```
First row in the table should be removed. 

**Spaces between tags**
Create protected email campaign with the following template.
```
<b> {{value1}}</b>{{value1}}
<b> {{value1}}</b>{{value1}}
<b> {{value1}}</b>{{value1}}
hello
```
First three rows should be collapsed to 1 `<br />`. 

**Test with CPF user's use case**
Use the template and CSV in the email. Empty lines should be removed.

## Deploy Notes

**New dependencies**:
- `cheerio` : HTML DOM parser and traversal

**Miscellaneous**
- Updated `package-lock.json` for frontend, backend and worker as per the [local templating module docs](https://github.com/opengovsg/postmangovsg/blob/develop/docs/local-module.md). Dev dependencies are also moved to dependencies as what docs suggested.

### CODE REVIEW

File: modules/postman-templating/src/template-client.ts [hunk 1]
```diff
@@ -189,6 +187,22 @@ export class TemplateClient {
      * removeEmptyLines
      */
     if (options.removeEmptyLines) {
+      // Remove empty tags so that collapsing of line breaks will work even if line contains empty tags
+      // Trim all empty spaces between tags so that they can be recognised as empty. E.g. <b> </b>
+      result = result.replace(/>\s+</g, '><')
```
Comment (jeantanzj) [inline modules/postman-templating/src/template-client.ts:192]: what about other whitespace characters

File: modules/postman-templating/src/template-client.ts [hunk 2]
```diff
@@ -189,6 +187,22 @@ export class TemplateClient {
...
+      const $ = cheerio.load(result, { xmlMode: true })
+      const emptyElements = (): cheerio.Cheerio =>
+        $(':empty').not('br, hr, img')
+
+      // Repeatedly remove until there are no more empty elements (maximum of 5 levels).
+      // E.g. After first pass <b><i></i><b> will become <b></b>.Therefore we will need another pass.
+      let levels = 1
+      while (emptyElements().length > 0 && levels <= 5) {
```
Comment (jeantanzj) [inline modules/postman-templating/src/template-client.ts:200]: should this be recursive?

File: modules/postman-templating/src/template-client.ts (hunk 1 above)
Comment (lamkeewei) [reply modules/postman-templating/src/template-client.ts:192]: Was thinking of collapsing all whitespace (tabs, etc) with the `\s` metacharacter, in case it was inserted by some other text editor the template author was using. But I realised something like this wouldn't get collapsed:

```
<b>
</b>
hello
```

Because it becomes the following:
```
<b><br></b>
<br>
Hello
```

Not sure how extensive should the stripping of empty tags be done though...

File: modules/postman-templating/src/template-client.ts (hunk 2 above)
Comment (lamkeewei) [reply modules/postman-templating/src/template-client.ts:200]: Yeah, I think a more efficient/better implementation might be to manually traverse the entire DOM tree and recursively remove nodes that are empty, compared to repeatedly calling the selector (which I assume does a full traversal again each time it's called). Let me try to see if I can implement that.

**Review by jeantanzj — APPROVED** [review]
