### PR TITLE
fix(frontend): fix test flakiness

### LINKED ISSUE #1161: Flaky frontend tests
**Describe the bug**
Some of the integration tests fail sporadically with the following error:
```
thrown: "Exceeded timeout of 5000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."
```

Specifically, this was experienced commonly with `src/components/dashboard/tests/integration/protected-email.test.tsx`. 

**To Reproduce**

1. Run `npm test`. It should fail every now and then.

**Expected behaviour**
All tests should pass 100% of the time.

**Possible solution**
1. Maybe we need to increase the timeout by adding `jest.setTimeout(SOME_LONG_TIMEOUT)` to `setupTests.ts`?
2. Maybe the test are not ending when they should be?

### PR DESCRIPTION
**Pull request by zwliew**
We were experiencing flaky tests as described in issue #1161.

## Problem

2 issues:
1. Some tests were failing with an error saying that the test exceeded the timeout of 5000ms.

2. The integration tests were written under the assumption that `REACT_APP_ANNOUNCEMENT_ACTIVE != "true"`. However, if it is set to `true`, the integration tests will break due to missing API endpoints and the tests not accounting for the need to dismiss the announcement modal.

Closes #1161

## Solution

- Increase the timeout of each test to 20s. 10s works fine locally on a MBP 16", but given that CI servers are likely slower, 2x the timeout to be safe.
- Add a dummy API mock for `/settings/announcement-version`
- Disable announcements for tests to enforce the assumption that `REACT_APP_ANNOUNCEMENT_ACTIVE=false`. This is fine because none of our tests rely on announcements.

Note: a longer term fix would be to add support for `announcement_version` in the API mocks, and configure the initial `announcement_version` appropriately during each test.

## Tests

All CI tests should pass reliably.

## Deploy Notes

 - Amplify no longer runs the tests. Any test failures should be caught on Travis during development. If a test failure does get to deployment, we can manually redeploy an older release.

### CODE REVIEW

**Comment by zwliew** [comment]
Could possibly explore using `--runInBand` or `maxWorkers=4` based on comments here: https://github.com/facebook/jest/issues/1524

File: frontend/src/setupTests.ts [hunk 1]
```diff
@@ -5,6 +5,8 @@ import { Crypto } from '@peculiar/webcrypto'
 import 'locales' // Locales necessary for I18nProvider
 import { server } from './test-utils'
 
+jest.setTimeout(20000)
```
Comment (lamkeewei) [inline frontend/src/setupTests.ts:8]: Perhaps we can introduce an environment variable with a fallback to a default for this? This way if we want to tune this for different environments, we do not need to make changes in the code.

Comment (zwliew) [reply frontend/src/setupTests.ts:8]: Good idea. I'll do that with a default of 20s.

Comment (lamkeewei) [reply frontend/src/setupTests.ts]: Do test this out on Amplify also with repeated runs.

Comment (zwliew) [reply frontend/src/setupTests.ts]: Yup, I'm doing so

**Comment by lamkeewei** [comment]
Also remember to remove running tests on Amplify.

**Comment by zwliew** [comment]
I'll continue running tests until deployment tonight, but this should fix the issue that you had locally as well as the timeout issues.

File: frontend/src/config.ts [hunk 2]
```diff
@@ -17,6 +18,9 @@ if (process.env.NODE_ENV === 'test') {
   gaInitializeOptions = {
     testMode: true,
   }
+
+  // Disable announcements in test environments
+  announcementActive = 'false'
```
Comment (zwliew) [inline frontend/src/config.ts:23]: What do you think about disabling announcements for tests? I think it's fine since none of our tests rely on announcements currently.

Comment (lamkeewei) [reply frontend/src/config.ts:23]: I think it's fine. Given that for most of the flows, that's not the main thing we're testing for.

**Review by lamkeewei — APPROVED** [review]
lgtm! This fixed the issues I was facing previously when running tests. Merge whenever you're ready.
